# Generated by Django 3.2.8 on 2021-12-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Portfolio.user'),
        ),
    ]
